### PR TITLE
More Plants Compatibility

### PR DESCRIPTION
**Pull request by thiago-rcarvalho**
Hey guys!

This PR makes **Rooms Expanded** compatible with [**More Plants**](https://steamcommunity.com/sharedfiles/filedetails/?id=2819853217) v1.0.4.

Can you check if everything is ok? I'd love to see Rooms Expanded working with More Plants! 😀

### CODE REVIEW

**Comment by pether-pg** [comment]
Thanks for the PR, but I'm not really sure what issue is being solved here. What plants are being missed by current code? What plants will benefit from the change?

**Comment by thiago-rcarvalho** [comment]
**More Plants** mod adds almost 30 decorative plants to the game but Rooms Expanded doesn't recognize them as decorative. So it's impossible, for example, to create a Botanical Garden room using non-vanilla, DLC, or Omni Flora plants.

Using the tag I added in More Plants v1.0.4 (_DecorMorePlants_) we can make it work without hard-coding all the plants names.

This PR brings compatibility between both mods.

**Comment by pether-pg** [comment]
Oh, I see. The name "More Plants" is so generic it confused me.
Please add a comment next to the tag to clarify what mod uses it. Provide mod's name, author and steam ID/link to avoid similar confusions in the future
thx!

**Comment by thiago-rcarvalho** [comment]
Thank you @pether-pg

PR updated!

**Pull request merged**
