### PR TITLE
Add Vietnamese translation for RoomExpanded

### PR DESCRIPTION
**Pull request by sant1ago-da-hanoi**
I re-translated your vi translation. Please merge ❤️

### CODE REVIEW

**Comment by pether-pg** [comment]
Hi! Thanks for the update!
There are a few rooms that are missed in the previous translation (rooms were not implemented at that time) and as a result your update does not include them.
Would you consider translating new rooms as well? I can see Space Museum and Pilot Help Center are missed, maybe something else as well...
Thanks!

**Comment by sant1ago-da-hanoi** [comment]
Sure, lad!

**Comment by sant1ago-da-hanoi** [comment]
> Hi! Thanks for the update! There are a few rooms that are missed in the previous translation (rooms were not implemented at that time) and as a result your update does not include them. Would you consider translating new rooms as well? I can see Space Museum and Pilot Help Center are missed, maybe something else as well... Thanks!

But I can't see any strings about those rooms, could you please update the template?

**Comment by pether-pg** [comment]
Sure, here is the newest one:
[roomsexpanded_template.zip](https://github.com/pether-pg/ONI_Mods_byPether/files/10940739/roomsexpanded_template.zip)

In the future - the mod auto generates the template if there is none found, you can remove old one and launch the game to get the newest version generated :)

**Pull request closed without merging**
